name = "email-to-telegram"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2000-01-01"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
